### ISSUE TITLE
Block Place Error

### ISSUE THREAD

**Issue by Racer10** [MC-Jinky/BasicAntiCheat#1]
My console gives the following error when any block is placed.

`[08:44:05] [Server thread/ERROR]: Could not pass event BlockPlaceEvent to BasicAntiCheat v1.0.3
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:320) ~[spigot.jar:git-Spigot-9de398a-9c887d4]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot.jar:git-Spigot-9de398a-9c887d4]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:529) ~[spigot.jar:git-Spigot-9de398a-9c887d4]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:514) ~[spigot.jar:git-Spigot-9de398a-9c887d4]
	at org.bukkit.craftbukkit.v1_14_R1.event.CraftEventFactory.callBlockPlaceEvent(CraftEventFactory.java:322) ~[spigot.jar:git-Spigot-9de398a-9c887d4]
	at net.minecraft.server.v1_14_R1.ItemStack.placeItem(ItemStack.java:203) ~[spigot.jar:git-Spigot-9de398a-9c887d4]
	at net.minecraft.server.v1_14_R1.PlayerInteractManager.a(PlayerInteractManager.java:468) ~[spigot.jar:git-Spigot-9de398a-9c887d4]
	at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1238) ~[spigot.jar:git-Spigot-9de398a-9c887d4]
	at net.minecraft.server.v1_14_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:27) ~[spigot.jar:git-Spigot-9de398a-9c887d4]
	at net.minecraft.server.v1_14_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:1) ~[spigot.jar:git-Spigot-9de398a-9c887d4]
	at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[spigot.jar:git-Spigot-9de398a-9c887d4]
	at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) [spigot.jar:git-Spigot-9de398a-9c887d4]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(SourceFile:144) [spigot.jar:git-Spigot-9de398a-9c887d4]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [spigot.jar:git-Spigot-9de398a-9c887d4]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(SourceFile:118) [spigot.jar:git-Spigot-9de398a-9c887d4]
	at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:910) [spigot.jar:git-Spigot-9de398a-9c887d4]
	at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:903) [spigot.jar:git-Spigot-9de398a-9c887d4]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(SourceFile:127) [spigot.jar:git-Spigot-9de398a-9c887d4]
	at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:887) [spigot.jar:git-Spigot-9de398a-9c887d4]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:820) [spigot.jar:git-Spigot-9de398a-9c887d4]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]
Caused by: java.lang.NoSuchMethodError: org.bukkit.entity.Player.getTargetBlock(I)Lorg/bukkit/block/Block;
	at me.jinky.checks.world.PlaceCheck.performCheck(PlaceCheck.java:67) ~[?:?]
	at me.jinky.handlers.BlockHandler.onPlace(BlockHandler.java:28) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_221]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_221]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_221]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_221]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316) ~[spigot.jar:git-Spigot-9de398a-9c887d4]
	... 20 more`

**Comment by Racer10** [comment]
Also when breaking blocks in survival (but not creative) I get this

`[08:56:11] [Server thread/ERROR]: Could not pass event BlockBreakEvent to BasicAntiCheat v1.0.3
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:320) ~[spigot.jar:git-Spigot-9de398a-9c887d4]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot.jar:git-Spigot-9de398a-9c887d4]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:529) ~[spigot.jar:git-Spigot-9de398a-9c887d4]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:514) ~[spigot.jar:git-Spigot-9de398a-9c887d4]
	at net.minecraft.server.v1_14_R1.PlayerInteractManager.breakBlock(PlayerInteractManager.java:295) ~[spigot.jar:git-Spigot-9de398a-9c887d4]
	at net.minecraft.server.v1_14_R1.PlayerInteractManager.a(PlayerInteractManager.java:254) ~[spigot.jar:git-Spigot-9de398a-9c887d4]
	at net.minecraft.server.v1_14_R1.PlayerInteractManager.a(PlayerInteractManager.java:230) ~[spigot.jar:git-Spigot-9de398a-9c887d4]
	at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1185) ~[spigot.jar:git-Spigot-9de398a-9c887d4]
	at net.minecraft.server.v1_14_R1.PacketPlayInBlockDig.a(SourceFile:40) ~[spigot.jar:git-Spigot-9de398a-9c887d4]
	at net.minecraft.server.v1_14_R1.PacketPlayInBlockDig.a(SourceFile:10) ~[spigot.jar:git-Spigot-9de398a-9c887d4]
	at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[spigot.jar:git-Spigot-9de398a-9c887d4]
	at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) [spigot.jar:git-Spigot-9de398a-9c887d4]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(SourceFile:144) [spigot.jar:git-Spigot-9de398a-9c887d4]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [spigot.jar:git-Spigot-9de398a-9c887d4]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(SourceFile:118) [spigot.jar:git-Spigot-9de398a-9c887d4]
	at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:910) [spigot.jar:git-Spigot-9de398a-9c887d4]
	at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:903) [spigot.jar:git-Spigot-9de398a-9c887d4]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(SourceFile:127) [spigot.jar:git-Spigot-9de398a-9c887d4]
	at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:887) [spigot.jar:git-Spigot-9de398a-9c887d4]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:820) [spigot.jar:git-Spigot-9de398a-9c887d4]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]
Caused by: java.lang.NoSuchMethodError: org.bukkit.entity.Player.getTargetBlock(I)Lorg/bukkit/block/Block;
	at me.jinky.checks.world.BreakCheck.performCheck(BreakCheck.java:109) ~[?:?]
	at me.jinky.handlers.BlockHandler.onBreak(BlockHandler.java:45) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_221]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_221]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_221]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_221]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316) ~[spigot.jar:git-Spigot-9de398a-9c887d4]
	... 20 more`

**Comment by MC-Jinky** [comment]
Please update to the latest Spigot build and see if it still causes errors. Your build of spigot is known to have NoSuchMethod found errors

**Comment by Racer10** [comment]
Freshly updated, still getting the same errors. Here they are in case anything changed.

`[09:16:23] [Server thread/ERROR]: Could not pass event BlockPlaceEvent to BasicAntiCheat v1.0.3
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:320) ~[spigot.jar:git-Spigot-798ea6a-2012f1e]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot.jar:git-Spigot-798ea6a-2012f1e]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:529) ~[spigot.jar:git-Spigot-798ea6a-2012f1e]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:514) ~[spigot.jar:git-Spigot-798ea6a-2012f1e]
	at org.bukkit.craftbukkit.v1_14_R1.event.CraftEventFactory.callBlockPlaceEvent(CraftEventFactory.java:322) ~[spigot.jar:git-Spigot-798ea6a-2012f1e]
	at net.minecraft.server.v1_14_R1.ItemStack.placeItem(ItemStack.java:203) ~[spigot.jar:git-Spigot-798ea6a-2012f1e]
	at net.minecraft.server.v1_14_R1.PlayerInteractManager.a(PlayerInteractManager.java:473) ~[spigot.jar:git-Spigot-798ea6a-2012f1e]
	at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1238) ~[spigot.jar:git-Spigot-798ea6a-2012f1e]
	at net.minecraft.server.v1_14_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:27) ~[spigot.jar:git-Spigot-798ea6a-2012f1e]
	at net.minecraft.server.v1_14_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:1) ~[spigot.jar:git-Spigot-798ea6a-2012f1e]
	at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[spigot.jar:git-Spigot-798ea6a-2012f1e]
	at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) [spigot.jar:git-Spigot-798ea6a-2012f1e]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(SourceFile:144) [spigot.jar:git-Spigot-798ea6a-2012f1e]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [spigot.jar:git-Spigot-798ea6a-2012f1e]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(SourceFile:118) [spigot.jar:git-Spigot-798ea6a-2012f1e]
	at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:909) [spigot.jar:git-Spigot-798ea6a-2012f1e]
	at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:902) [spigot.jar:git-Spigot-798ea6a-2012f1e]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(SourceFile:127) [spigot.jar:git-Spigot-798ea6a-2012f1e]
	at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:886) [spigot.jar:git-Spigot-798ea6a-2012f1e]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:819) [spigot.jar:git-Spigot-798ea6a-2012f1e]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]
Caused by: java.lang.NoSuchMethodError: org.bukkit.entity.Player.getTargetBlock(I)Lorg/bukkit/block/Block;
	at me.jinky.checks.world.PlaceCheck.performCheck(PlaceCheck.java:67) ~[?:?]
	at me.jinky.handlers.BlockHandler.onPlace(BlockHandler.java:28) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_221]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_221]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_221]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_221]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316) ~[spigot.jar:git-Spigot-798ea6a-2012f1e]
	... 20 more`

`[09:16:27] [Server thread/ERROR]: Could not pass event BlockBreakEvent to BasicAntiCheat v1.0.3
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:320) ~[spigot.jar:git-Spigot-798ea6a-2012f1e]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot.jar:git-Spigot-798ea6a-2012f1e]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:529) ~[spigot.jar:git-Spigot-798ea6a-2012f1e]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:514) ~[spigot.jar:git-Spigot-798ea6a-2012f1e]
	at net.minecraft.server.v1_14_R1.PlayerInteractManager.breakBlock(PlayerInteractManager.java:295) ~[spigot.jar:git-Spigot-798ea6a-2012f1e]
	at net.minecraft.server.v1_14_R1.PlayerInteractManager.a(PlayerInteractManager.java:254) ~[spigot.jar:git-Spigot-798ea6a-2012f1e]
	at net.minecraft.server.v1_14_R1.PlayerInteractManager.a(PlayerInteractManager.java:230) ~[spigot.jar:git-Spigot-798ea6a-2012f1e]
	at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1185) ~[spigot.jar:git-Spigot-798ea6a-2012f1e]
	at net.minecraft.server.v1_14_R1.PacketPlayInBlockDig.a(SourceFile:40) ~[spigot.jar:git-Spigot-798ea6a-2012f1e]
	at net.minecraft.server.v1_14_R1.PacketPlayInBlockDig.a(SourceFile:10) ~[spigot.jar:git-Spigot-798ea6a-2012f1e]
	at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[spigot.jar:git-Spigot-798ea6a-2012f1e]
	at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) [spigot.jar:git-Spigot-798ea6a-2012f1e]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(SourceFile:144) [spigot.jar:git-Spigot-798ea6a-2012f1e]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [spigot.jar:git-Spigot-798ea6a-2012f1e]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(SourceFile:118) [spigot.jar:git-Spigot-798ea6a-2012f1e]
	at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:909) [spigot.jar:git-Spigot-798ea6a-2012f1e]
	at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:902) [spigot.jar:git-Spigot-798ea6a-2012f1e]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(SourceFile:127) [spigot.jar:git-Spigot-798ea6a-2012f1e]
	at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:886) [spigot.jar:git-Spigot-798ea6a-2012f1e]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:819) [spigot.jar:git-Spigot-798ea6a-2012f1e]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]
Caused by: java.lang.NoSuchMethodError: org.bukkit.entity.Player.getTargetBlock(I)Lorg/bukkit/block/Block;
	at me.jinky.checks.world.BreakCheck.performCheck(BreakCheck.java:109) ~[?:?]
	at me.jinky.handlers.BlockHandler.onBreak(BlockHandler.java:45) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_221]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_221]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_221]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_221]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316) ~[spigot.jar:git-Spigot-798ea6a-2012f1e]
	... 20 more`

**Comment by MC-Jinky** [comment]
That’s very strange. Can you tell me the output of /version and I’ll check out the issue in about an hour when I get home

**Comment by Racer10** [comment]
This server is running CraftBukkit version git-Spigot-798ea6a-2012f1e (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)

**Comment by MC-Jinky** [comment]
I’d prefer if you could, join the discord server and open a new ticket with -new {subject} and provide me with your server id. You can join the discord by going to the plugin page and hitting “Ask questions / Get Support” on the right side

**Comment by MC-Jinky** [comment]
Fixed in version 1.0.4. Thanks for the help!
